# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["development"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_VARIABLE: ${{ vars.MY_VARIABLE }}
  MY_SECRET: ${{ secrets.MY_SECRET }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  step1:
    environment: development
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: List root
        run: ls / -la

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print contents of hola.txt 2
        run: cat hola.txt

      - name: Print contents of my secret
        run: echo $MY_SECRET

      - name: Print contents of my variable
        run: echo $MY_VARIABLE

  step2:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Starting step 2
        run: this is part of the dev pipeline
